### ISSUE TITLE
Mention installing prerequisites for using Tauri 

### ISSUE THREAD

**Issue by arcanistzed** [AyanavaKarmakar/tauri-t3-app#12]
https://next--tauri.netlify.app/next/guides/getting-started/prerequisites/

I couldn't figure out how to get the app to build until I found this page, so I think it might be a good idea to add that to the README in case anyone else has the same issue in the future.

Thank you for the great template!

**Comment by AyanavaKarmakar** [comment]
The "Prerequisites" totally slipped my mind! Thank you for taking the time to share your suggestion - it will be helpful to others in the future.
